"""迁移脚本

Revision ID: 26c2a450ecf0
Revises: 
Create Date: 2026-05-10 02:32:53.526875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c2a450ecf0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_user',
    sa.Column('email', sa.String(length=64), nullable=True, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('is_vip', sa.Boolean(), nullable=False, comment='是否VIP'),
    sa.Column('vip_expire_at', sa.DateTime(timezone=True), nullable=True, comment='VIP过期时间'),
    sa.Column('daily_summary_count', sa.Integer(), nullable=False, comment='每日总结次数'),
    sa.Column('last_summary_date', sa.Date(), nullable=True, comment='最后总结日期'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_sys_user_created_at'), 'sys_user', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_user_email'), 'sys_user', ['email'], unique=True)
    op.create_index(op.f('ix_sys_user_id'), 'sys_user', ['id'], unique=False)
    op.create_index(op.f('ix_sys_user_updated_at'), 'sys_user', ['updated_at'], unique=False)
    op.create_table('sys_order',
    sa.Column('order_no', sa.String(length=64), nullable=False, comment='订单号'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='金额'),
    sa.Column('currency', sa.String(length=64), nullable=False, comment='货币'),
    sa.Column('status', sa.String(length=64), nullable=False, comment='状态'),
    sa.Column('plan_type', sa.String(length=64), nullable=False, comment='套餐类型'),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True, comment='Stripe Session ID'),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True, comment='Stripe Payment Intent ID'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='支付时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单表'
    )
    op.create_index(op.f('ix_sys_order_created_at'), 'sys_order', ['created_at'], unique=False)
    op.create_index(op.f('ix_sys_order_id'), 'sys_order', ['id'], unique=False)
    op.create_index(op.f('ix_sys_order_order_no'), 'sys_order', ['order_no'], unique=True)
    op.create_index(op.f('ix_sys_order_paid_at'), 'sys_order', ['paid_at'], unique=False)
    op.create_index(op.f('ix_sys_order_stripe_session_id'), 'sys_order', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_sys_order_updated_at'), 'sys_order', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sys_order_user_id'), 'sys_order', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sys_order_user_id'), table_name='sys_order')
    op.drop_index(op.f('ix_sys_order_updated_at'), table_name='sys_order')
    op.drop_index(op.f('ix_sys_order_stripe_session_id'), table_name='sys_order')
    op.drop_index(op.f('ix_sys_order_paid_at'), table_name='sys_order')
    op.drop_index(op.f('ix_sys_order_order_no'), table_name='sys_order')
    op.drop_index(op.f('ix_sys_order_id'), table_name='sys_order')
    op.drop_index(op.f('ix_sys_order_created_at'), table_name='sys_order')
    op.drop_table('sys_order')
    op.drop_index(op.f('ix_sys_user_updated_at'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_id'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_email'), table_name='sys_user')
    op.drop_index(op.f('ix_sys_user_created_at'), table_name='sys_user')
    op.drop_table('sys_user')
    # ### end Alembic commands ###
